# Lab 5

1. 提交作業之前，建議可以先點選上方工具列的**Kernel**，再選擇**Restart & Run All**，檢查一下是否程式跑起來都沒有問題，最後記得儲存。
2. 請先填上下方的姓名(name)及學號(stduent_id)再開始作答，例如：
```python
name = "我的名字"
student_id= "B06201000"
```
3. 演算法的實作可以參考[lab-5](https://yuanyuyuan.github.io/itcm/lab-5.html), 有任何問題歡迎找助教詢問。
4. **Deadline: 12/11(Wed.)**

In [1]:
name = "彭盛皓"
student_id = "B06201008"

---

# Exercise 3
---
### Analyse the convergence properties of the Jacobi and Gauss-Seidel methods for the solution of a linear system whose matrix is
### $$\left[\begin{matrix}
    \alpha &&0 &&1\\
    0 &&\alpha &&0\\
    1 &&0 &&\alpha
    \end{matrix}\right],
    \quad \quad
    \alpha \in \mathbb{R}.$$

> Please write down your analysis in detail with LaTeX/Markdown at here. And if you need to do some numerical experiments, you can add more blocks to test your codes at below.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA

### First, we need to construct a matrix like the problem given.

In [3]:
def construct_matrix(
    a,
    m
):
    A = np.diag(a * np.ones(m))
    A[0,m-1] = 1
    A[m-1,0] = 1
    
    return A

Test for the function.

In [30]:
A = construct_matrix(2,3)
print(A)

[[2. 0. 1.]
 [0. 2. 0.]
 [1. 0. 2.]]


### Second, construct the Jacobi method and Gauss-seidel method.

#### 1. Jacobi method

In [11]:
def jacobi(A,b,N=100,x=None,tol=1e-15):
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = np.diag(A)
    R = A - np.diagflat(D)
    
    # Iterate for N times                                                                                                                                                                          
    count = 0
    for i in range(N):
        count += 1
        x2 = (b - np.dot(R,x)) / D
        delta = LA.norm(x - x2)
        if delta < tol:
            print("f converges within %d iterations with given tolerance."%count)
            return x2
        x = x2
    print("f did not converge within %d iterations with given tolerance."%N)

    return x

In [31]:
jacobi(A,[3,4,5],1000,None,1e-15)

f converges within 53 iterations with given tolerance.


array([0.33333333, 2.        , 2.33333333])

#### 2. Gauss-seidel method

In [7]:
def gaussSeidel(A,b,N=100,x=None,tol=1e-15):
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    L = np.tril(A)
    R = A - L
    
    # Iterate for N times                                                                                                                                                                          
    count = 0
    for i in range(N):
        count += 1
        x2 = LA.inv(L) @ (b - np.dot(R,x))
        delta = LA.norm(x - x2)
        if delta < tol:
            print("f converges within %d iterations with given tolerance."%count)
            return x2
        x = x2
    print("f did not converge within %d iterations with given tolerance."%N)
    return x

In [21]:
gaussSeidel(A,[3,4,5],1000,None,1e-10)

f converges within 19 iterations with given tolerance.


array([0.33333333, 2.        , 2.33333333])

### Third, discuss the convergence of these iteration methods.

Let the iteration method be written 
$$x^{(k)}=Tx^{(k-1)}+c$$ for each $k=1,2,3,...$

#### Lemma
If the spectral radius satisfies $\rho (T)<1$, then $(I-T)^{-1}$ exists, and 
$$(I-T)^{-1}=I+T+T^2+...=\sum_{j=0}^{\infty}T^j$$

We have the theorem of convergence below:

#### Theorem 
For any initial status $x^{(0)}\in R^n$, the sequence $\{x^{(k)}\}_{k=0}^{\infty}$defined by 
$$x^{(k)}=Tx^{(k-1)}+c$$ for each $k\geq 1$,
converges to the unique solution of $x=Tx+c$ if and only if $\rho (T)<1$

In our case, the matrix of the form $$\left[\begin{matrix}
    \alpha &&0 &&1\\
    0 &&\alpha &&0\\
    1 &&0 &&\alpha
    \end{matrix}\right],
    \quad \quad
    \alpha \in \mathbb{R}.$$
has the special situation if $\alpha = 1$:

In [25]:
A = construct_matrix(1,3)

In [26]:
jacobi(A,[3,4,5],1000,None,1e-15)

f did not converge within 1000 iterations with given tolerance.


array([-1000.,     4.,  1000.])

In [27]:
gaussSeidel(A,[3,4,5],1000,None,1e-10)

f did not converge within 1000 iterations with given tolerance.


array([-1995.,     4.,  2000.])

Since, if $\alpha = 1$, then $(I-T)^{-1}$ is not invertible.

#### Corollary
If $||T||<1$ for any natural norm and $c$ is a given vector, then the sequence $\{x^{(k)}\}_{k=0}^{\infty}$defined by 
$$x^{(k)}=Tx^{(k-1)}+c$$ for each $k\geq 1$,
converges, for any $x^{(0)}\in R^n$, to a vector of $x\in R^n$, with $x=Tx+c$, and the following error bound hold:\
$(i)$ $||x-x^{(k)}||\leq ||T||^k||x^{(0)}-x||$\
$(ii)$ $||x-x^{(k)}||\leq \frac{||T||^k}{1-||T||}||x^{(1)}-x^{(0)}||$

By $(i)$, $||x-x^{(k)}||\approx \rho(T)^k||x^{(0)}-x||$

### Finally, we have the result.

If $A$ is strictly diagonally dominant, then for any choice of $X^{(0)}$, both the Jacobi and Gauss-Seidel methods give sequences $\{x^{(k)}\}_{k=0}^{\infty}$ that converges to the unique solution of $Ax=b$.